apiVersion: skaffold/v2beta28
kind: Config
metadata:
  name: javabin-sommer
build:
  artifacts:
  - image: test1
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - web-deployment.yaml
