apiVersion: apps/v1
kind: Deployment
metadata:
  name: web01
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web01
  template:
    metadata:
      labels:
        app: web01
    spec:
      containers:
        - image: test1
          name: web01
          ports:
          - name: http
            containerPort: 8080
            protocol: TCP
          resources:
            limits:
              cpu: 2000m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 64Mi
---
apiVersion: v1
kind: Service
metadata:
  name: web01
  labels:
    app: web01
spec:
  selector:
    app: web01
  ports:
    - port: 80
      name: http
      protocol: TCP
      targetPort: http
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web01
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: web01
            port:
              number: 80
